name: Build GitBook
on: [push]

# GITHUB_TOKEN must be given read/write permissions for this to work.
# In Settings -> Actions -> General -> Workflow permissions, select "Read and write permissions"
# The GitBook code will be stored in the gh-pages branch
# GitHub Pages must be configured to build from gh-pages

jobs:
  build:
    if: github.ref == 'refs/heads/main' # change this if the primary branch has a different name
    name: Build Gitbook
    runs-on: ubuntu-latest
    steps:
      # Check out the repo first
      - name: Checkout code
        uses: actions/checkout@v2
      # Run this action to publish gitbook
      - name: Publish
        uses: tuliren/publish-gitbook@v1.0.0
        with:
          # specify either github_token or personal_token
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # personal_token: ${{ secrets.PERSONAL_TOKEN }}
